apiVersion: v1
kind: Service
metadata:
 name: postgres-service
 label:
  name: postgres-service
  team: rus

spec:
 ports:
 - port: 5432
   targetPort: 5432
 selector:
  matchLabels:
   name: postgres-pod
   team: rus
