apiVersion: v1
kind: Service
metadata:
 name: redis-service
 label:
  name: redis-service
  team: rus

spec:
 ports:
 - port: 6379
   targetPort: 6379
 selector:
  matchLabels:
   name: redis-pod
   team: rus
