apiVersion: v1
kind: Pod
metadata:
 name: voting_app-pod
 label:
  name: voting_app-pod
  team: rus

spec:
 containers:
 - name: voting_app-container
   image: dockersamples/examplevotingapp_vote
   ports:
   - containerPort: 80
